sudo: false

language: java

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk15
  - openjdk16
  - openjdk17
  
cache:
  directories:
    - "$HOME/.m2/repository"

script:
  - if [[ $TRAVIS_PULL_REQUEST = false ]] && [[ $TRAVIS_BRANCH = master ]] && [[ $TRAVIS_JDK_VERSION = openjdk15 ]]; then GOAL=deploy; else GOAL=package; fi
  - echo $GOAL
  - mvn -U $GOAL
  - docker build -t sample-oauth-server:$COMMIT ./addons/oauth

deploy:
  provider: script
  script: bash ./addons/oauth/deploy.sh
  on:
    all_branches: true
    jdk: openjdk11

after_success: mvn -q coveralls:report -DrepoToken=$COVERALLS_TOKEN
