#
# Copyright © 2013-2020, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

logging:
  level: INFO

application:
  id: oauth-sample

web:
  server:
    port: 8090

rest:
  path: /api


#Security configuration set to use the OAuth addon
security:
  realms: OAuthRealm
  web:
    urls:
      - pattern: /logout
        filters: logout
      - pattern: /callback
        filters: oauthCallback
      - pattern: /api/**
        filters: oauth

 #OAuth addon configuration for an Authorization code flow usage
  oauth:
    discoveryDocument: http://localhost:8080/auth/realms/SeedSamplesRealm/.well-known/openid-configuration
    redirect: http://localhost:8090/callback
    scopes: [email openid profile CodeFlowScope]
    clientId: SeedStackClientCodeFlow
    clientSecret: 3545c109-9cf0-4ccf-82aa-89464f798844
    allowedAudiences: account
    autoFetchUserInfo: true
