#
# Copyright © 2013-2020, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

logging:
  level: INFO

application:
  id: oauth-sample

#As the authentication server is running on port 8080, this sample runs on port 8090
web:
  server:
    port: 8090

rest:
  path: /api

#Secure the api with Oauth
security:
  realms: OAuthRealm
  web:
    urls:
      - pattern: /api/**
        filters: oauth

#The request is having a token in its Authorization header
#This configuration is for the oauth addon to validate the token
  oauth:
    discoveryDocument: http://localhost:8080/auth/realms/SeedSamplesRealm/.well-known/openid-configuration
    allowedAudiences: account

