#
# Copyright © 2013-2020, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

logging:
  level: INFO

#The Sample's Authentication server listens on the 8080 port, we are using here port 8090
web:
  server:
    port: 8090

application:
  id: oauth-sample

rest:
  path: /api

#The api is secured with OAuth configuration
security:
  realms: OAuthRealm
  web:
    urls:
      - pattern: /logout
        filters: logout
      - pattern: /api/**
        filters: oauth

#The OAuth configuration required for a PKCE exchange
#The client secret and ID are managed frontend side.
#The PKCE sample configuration validates the bearer token coming with the request Authorization header
  oauth:
    discoveryDocument: http://localhost:8080/auth/realms/SeedSamplesRealm/.well-known/openid-configuration
    allowedAudiences: ["http://localhost:8090/api/profile","account"]
    scopes: [openid, email, profile, pkceScope]
    autoFetchUserInfo: true
