#
# Copyright © 2013-2020, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

logging:
  level: INFO

application:
  id: oauth-sample

#Using feign addon to call the secured API
feign:
  endpoints:
    org.seedstack.samples.oauth.api.SecuredApi:
      baseUrl: http://localhost:8090/api
      decoder: feign.jackson.JacksonDecoder

# Oauth configuration, only requires clientID & client secret
# The authentication server must have been configured to accept credential flow from this client
security:
  realms: OAuthRealm
  oauth:
    discoveryDocument: http://localhost:8080/auth/realms/SeedSamplesRealm/.well-known/openid-configuration
    clientId: SeedStackClientCredentials
    clientSecret: 8b8d20f8-281d-41b4-84ef-be9418b4a21c